# Generated by Django 4.2.4 on 2023-08-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_editor_news_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor_news',
            name='news_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
