# Generated by Django 4.2.4 on 2023-08-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_1', models.CharField(max_length=50)),
                ('service_2', models.CharField(max_length=50)),
                ('service_des', models.TextField()),
            ],
        ),
    ]
